spring.application.name=notification-service
server.port=8084

# MongoDB - Technology Change for bonus points
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=medilink_notifications
spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Keycloak / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/medilink
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
